
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/overview',
        {
          type: 'category',
          label: 'Installation',
          items: [
            'getting-started/installation/overview',
            'getting-started/installation/greptimedb-standalone',
            'getting-started/installation/greptimedb-cluster',
            'getting-started/installation/greptimedb-dashboard'
          ]
        },
        {
          type: 'category',
          label: 'Quick Start',
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/quick-start'
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'user-guide/overview',
        {
          type: 'category',
          label: 'Concepts',

          items: [
            'user-guide/concepts/overview',
            'user-guide/concepts/why-greptimedb',
            'user-guide/concepts/data-model',
            'user-guide/concepts/architecture',
            'user-guide/concepts/storage-location',
            'user-guide/concepts/key-concepts',
            'user-guide/concepts/features-that-you-concern'
          ]
        },
        {
          type: 'category',
          label: 'Clients',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/clients'
            }
          ]
        },
        {
          type: 'category',
          label: 'Migrate to GreptimeDB',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/migrate-to-greptimedb'
            }
          ]
        },
        'user-guide/table-management',
        {
          type: 'category',
          label: 'Write Data',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/write-data'
            }
          ]
        },
        {
          type: 'category',
          label: 'Query Data',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/query-data'
            }
          ]
        },
        {
          type: 'category',
          label: 'Continuous Aggregation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/continuous-aggregation'
            }
          ]
        },
        {
          type: 'category',
          label: 'Client Libraries',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/client-libraries'
            }
          ]
        },
        {
          type: 'category',
          label: 'Python Scripts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/python-scripts'
            }
          ]
        },
        'user-guide/cluster',
        {
          type: 'category',
          label: 'Operations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/operations'
            }
          ]
        },
        'user-guide/upgrade',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/command-lines',
        {
          type: 'category',
          label: 'SQL',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/sql'
            }
          ]
        },
        'reference/telemetry'
      ]
    },
    {
      type: 'link',
      label: 'Release Notes',
      href: '/blog/release-notes/all-releases'
      
    },
    
  ]
};

export default sidebars;
