blank_issues_enabled: false
contact_links:
  - name: GreptimeDB Discussions
    url: https://github.com/orgs/GreptimeTeam/discussions
    about: Ask GreptimeDB usage and support questions
  - name: Greptime community Slack
    url: https://greptime.com/slack
    about: Talk with GreptimeDB users and maintainers
