// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomContent: typeof import('./.vitepress/theme/components/CustomContent.vue')['default']
    Header: typeof import('./.vitepress/theme/components/Header.vue')['default']
    Layout: typeof import('./.vitepress/theme/components/Layout.vue')['default']
  }
}
