/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DocsTemplate: typeof import('./.vitepress/theme/components/DocsTemplate.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/Footer.vue')['default']
  }
}
